# Generated by Django 5.0.7 on 2024-07-29 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_desc_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='id_product',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
